version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN }}
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_REGISTRY_REGISTRY_GH_ORG_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: UTC
    open-pull-requests-limit: 10
    target-branch: main
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - dependabot
    registries:
      - npm-registry-registry-npmjs-org
      - npm-github
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:00'
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
