name: Run Checks

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore the build folders
        uses: actions/cache/restore@v4
        with:
          path: build/
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Run linting
        run: npm run lint
