name: CI
permissions:
  contents: read

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    uses: ./.github/workflows/build.yml

  check:
    needs: build
    uses: ./.github/workflows/check.yml

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, check]
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: ./.github/workflows/release.yml
